config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tips#index"
  resources :tips do
    resources :suspects
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/suspect.rb
class Suspect < ApplicationRecord
  default_scope { order('updated_at DESC') }
  belongs_to :tip
end

app/models/tip.rb
class Tip < ApplicationRecord
  default_scope { order('updated_at DESC') }
  has_many :suspects, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/suspects_controller.rb
class SuspectsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    def new
      @tip = Tip.find(params[:tip_id])
      @suspect = Suspect.new
    end

    def create
      @tip = Tip.find(params[:tip_id])
      @suspect = @tip.suspects.create(suspect_params)
      redirect_to tip_path(@tip)
    end

    def edit
      @tip = Tip.find(params[:tip_id])
      @suspect = Suspect.find(params[:id])
    end

    def update
      @tip = Tip.find(params[:tip_id])
      @suspect = Suspect.find(params[:id])
      if @tip.user == current_user && !@tip.user.nil?
      @suspect.update(suspect_params)
    else
      flash[:alert] = "Only the person that provided the tip can edit it."
    end
      redirect_to tip_path(@tip)
    end

    def destroy
      @tip = Tip.find(params[:tip_id])
      @suspect = Suspect.find(params[:id])
      if @tip.user == current_user && !@tip.user.nil?
      @suspect.destroy
    else
      flash[:alert] = "Only the person that provided the tip can delete it."
    end
      redirect_to tip_path(@tip)
    end

    private
    def suspect_params
      params.require(:suspect).permit(:img_url,:race,:gender,:height,:weight,:hair,:clothing,:weapons,:vehicle,:year,:make,:model,:color,:license,:state,:description,:tip_id)
    end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  def index
    @tips = Tip.all
  end

  def new
    @tip = Tip.new
  end

  def create
    @tip = Tip.create!(tip_params.merge(user: current_user))
    redirect_to tip_path(@tip)
  end

  def show
    @tip = Tip.find(params[:id])
  end

  def edit
    @tip = Tip.find(params[:id])
  end

  def update
    @tip = Tip.find(params[:id])
    if @tip.user == current_user && !@tip.user.nil?
    @tip.update(tip_params)
  else
    flash[:notice] = "Please don't edit someone else's tip."
  end
  redirect_to tip_path(@tip)
  end

  def destroy
    @tip = Tip.find(params[:id])
    if @tip.user == current_user && !@tip.user.nil?
    @tip.destroy
  else
    flash[:alert] = "Only the creator of the tip can delete it."
  end
    redirect_to tips_path
  end

  private
  def tip_params
    params.require(:tip).permit(:offense, :location, :img_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snitch</title>
    <%= csrf_meta_tags %>
    <%# <embed src="otgenasispushit.mp3" autostart="true" loop="true" hidden="true"><embed> #%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
  </head>

  <body background = "/assets/snitch.jpg">
    <div class="superhero">
    <% if !current_user %>
      <%= link_to "Private Sign Up", new_user_registration_path %> |
      <%= link_to "Private Sign In", new_user_session_path %>
    <% else %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <%= '*' * (current_user.email.size - 4) + current_user.email[-4..-1] %>
    <% end %>
  </div>
  <div class="superhero">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
    <%= yield %>
  </body>
</html>

app/views/suspects/_form.html.erb
<div class="paste">
<%= form_for [@tip, @suspect] do |f| %>
  <section class="input">
  <p>
  <%= f.label :img_url %>
  <%= f.text_field :img_url %>
  </p>
  <p>
  <%= f.label :race %>
  <%= f.select :race, ["", "AMERICAN INDIAN / ALASKA NATIVE", "ASIAN", "BLACK / AFRICAN AMERICAN", "NATIVE HAWAIIAN / PACIFIC ISLANDER", "WHITE", "HISPANIC", "OTHER"]%>
  </p>
  <p>
  <%= f.label :gender %>
  <%= f.select :gender, ["", "MALE", "FEMALE", "TRANSGENDER"]%>
  </p>
  <p>
  <%= f.label :height %>
  <%= f.select :height, ["","4ft","4ft 3in","4ft 6in","4ft 9in","5ft","5ft 3in","5ft 6in","5ft 9in","6ft","6ft 3in","6ft 6in","6ft 9in","7ft","7ft 3in","7ft 6in"] %>
  </p>
  <p>
  <%= f.label :weight %>
  <%= f.select :weight, ["","100","110","120","130","140","150","160","170","180","190","200","210","220","230","240","250","260","270","280","290","300","310","320","330","340","350+"] %>
  </p>
  <p>
  <%= f.label :hair %>
  <%= f.text_field :hair %>
  </p>
  <p>
  <%= f.label :clothing %>
  <%= f.text_area :clothing %>
  </p>
  <p>
  <%= f.label :weapons %>
  <%= f.text_area :weapons %>
  </p>
  </section>

  <section class="input">
  <p>
  <%= f.label :vehicle %>
  <%= f.check_box :vehicle %>
  </p>
  <p>
  <%= f.label :year %>
  <%= f.select :year, ["","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017"] %>
  </p>
  <p>
  <%= f.label :make %>
  <%= f.text_field :make %>
  </p>
  <p>
  <%= f.label :model %>
  <%= f.text_field :model %>
  </p>
  <p>
  <%= f.label :color %>
  <%= f.text_field :color %>
  </p>
  <p>
  <%= f.label :license %>
  <%= f.text_field :license %>
  </p>
  <p>
  <%= f.label :state %>
  <%= f.select :state, ["","AL","AK","AZ","AR","CA","CO","CT","DC","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"] %>
  </p>
  <p>
  <%= f.label :description %>
  <%= f.text_area :description %>
  </p>
  </section>
  <span><%= f.submit %></span>
  <% end %>
</div>

app/views/suspects/edit.html.erb
<h2 class="ganggreen">Edit Suspect</h2>
<%= render "form" %>

app/views/suspects/new.html.erb
<h2 class="ganggreen">New Suspect</h2>
<%= render "form" %>

app/views/tips/_form.html.erb
<div class="putty">
<%= form_for @tip do |f| %>
  <p>
  <%= f.label :offense %>
  <%= f.text_field :offense %>
  </p>
  <p>
  <%= f.label :location %>
  <%= f.text_field :location %>
  </p>
  <p>
  <%= f.label :img_url %>
  <%= f.text_field :img_url %>
  </p>
  <%= f.submit %>
<% end %>
</div>

app/views/tips/edit.html.erb
<h2 class="ganggreen" id="edittip">Edit Tip</h2>
<%= render "form" %>

app/views/tips/index.html.erb
<h1>SNITCH</h1>
<br>
<div class="superhero">
<% if current_user %>
<%= link_to "Provide a New Tip", new_tip_path, :class => "superhero" %>
<% end %>
</div>
<article>
<% @tips.each do |tip| %>
  <section>
    <h2><%= link_to tip.offense, tip_path(tip), :class => "ganggreen" %></h2>
    <h3><%= tip.location %></h3>
    <time>Updated <%= tip.updated_at.strftime("%m/%d/%y") %></time>
    <time>at <%= tip.updated_at.strftime("%I:%M%p") %></time>
    <p><img src="<%= tip.img_url%>" class="crime"></p>
  </section>
<% end %>
</article>

app/views/tips/new.html.erb
<h2 class="ganggreen">New Tip</h2>
<%= render "form" %>

app/views/tips/show.html.erb
<%= link_to "&larr; Back".html_safe, tips_path, :class => "superhero" %>
<main>
  <div>
    <h3><%= @tip.offense %></h3><br>
    <h3><%= @tip.location %></h3><br>
    <h3><img src="<%= @tip.img_url %>" class="crime"></h3>
    <% if current_user %>
    <h3><%= link_to "Edit Tip", edit_tip_path(@tip), :class => "superhero" %></h3>
    <h3><%= link_to "Delete Tip", tip_path(@tip), :class => "superhero", method: :delete %></h3>
    <% end %>
  </div>
</main>
  <br>
  <h2 class="ganggreen">Suspect(s)</h2>
  <% if current_user %>
  <%= link_to "Add new suspect(s)", new_tip_suspect_path(@tip), :class => "superhero" %>
  <% end %>
  <br>
  <article>
  <% @tip.suspects.each do |suspect| %>
    <section>
        <h3><time>Updated <%= suspect.updated_at.strftime("%m/%d/%y") %></time></h3>
        <h3><time>at <%= suspect.updated_at.strftime("%I:%M%p") %></time></h3>
        <h3><img src="<%= suspect.img_url %>" class="crime"></h3>
        <h3>Race: <%= suspect.race %></h3>
        <h3>Gender: <%= suspect.gender %></h3>
        <h3>Height: <%= suspect.height %></h3>
        <h3>Weight: <%= suspect.weight %></h3>
        <h3>Hair: <%= suspect.hair %></h3>
        <h3>Clothing: <%= suspect.clothing %></h3>
        <h3>Weapons: <%= suspect.weapons %></h3>
        <% if suspect.vehicle? %>
        <h3>Vehicle: <%= suspect.vehicle %></h3>
        <h3>Year: <%= suspect.year %></h3>
        <h3>Make: <%= suspect.make %></h3>
        <h3>Model: <%= suspect.model %></h3>
        <h3>Color: <%= suspect.color %></h3>
        <h3>License Plate: <%= suspect.license %></h3>
        <h3>State: <%= suspect.state %></h3>
        <% end %>
        <h3>Description: <%= suspect.description %></h3>
      <div class="superhero">
      <% if current_user %>
      <%= link_to "Edit Suspect", edit_tip_suspect_path(@tip, suspect) %> |
      <%= link_to "Delete Suspect", tip_suspect_path(@tip, suspect), method: :delete %>
      </div>
      <% end %>
    </section>
    <% end %>
  </article>